### ISSUE TITLE
(MatchError) no match of right hand side value

### ISSUE THREAD

**Issue by Eptagone** [rockneurotiko/telegram_api_json#19]
Hi. I'm trying to export json files for the new release but I'm getting the following errors.
I'm using Debian
```
** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{reason: {:options, {:cacertfile, '/Users/mgarcial/Downloads/gartner_ca_bundle_20210429.pem', {:error, :enoent}}}, id: nil}}
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:313: TelegramApiJson.get_html/0
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:46: TelegramApiJson.tree/0
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:37: TelegramApiJson.scrape/0
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:41: TelegramApiJson.scrape_and_print/1
    nofile:1: (file)
    (stdlib 4.3) erl_eval.erl:748: :erl_eval.do_apply/7
** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{reason: {:options, {:cacertfile, '/Users/mgarcial/Downloads/gartner_ca_bundle_20210429.pem', {:error, :enoent}}}, id: nil}}
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:313: TelegramApiJson.get_html/0
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:46: TelegramApiJson.tree/0
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:37: TelegramApiJson.scrape/0
    (telegram_api_json 0.1.0) lib/telegram_api_json.ex:41: TelegramApiJson.scrape_and_print/1
    nofile:1: (file)
    (stdlib 4.3) erl_eval.erl:748: :erl_eval.do_apply/7
```

**Comment by rockneurotiko** [comment]
Fixed, my bad.

Can you check again, just to confirm that it works on your computer?

**Comment by Eptagone** [comment]
It's working again :3, thank you
